spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    enabled: on
    default-models-expand-depth: -1
    display-request-duration: true

logging:
  level:
    kr.co.wanted: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: helloWorld
  expiration_time: 86400000 # 300000 - 5분, 86400000 - 1일, 604800000 - 7일