server:
  port: 8088
  error:
    include-exception: false
    include-message: never
    include-stacktrace: on_param
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
    url: jdbc:mysql://127.0.0.1:3306/ryuqq?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      port: 6379
      host: 127.0.0.1

logging:
  level:
    com.zaxxer.hikari: DEBUG
    com.wanted.preonboarding: DEBUG

token:
  secret: "36bddb74-043c-4fcd-a17d-d7089bf65b90"
  expiration: 1800000000
  refresh_expiration: 86400000000



