### signup
POST {{host}}/auth/signup
Content-Type: application/json

{
  "userId": "aaa",
  "name":"testName",
  "password":"bbb"
}

### login
POST {{host}}/login
Content-Type: application/json

{
  "userId": "admin",
  "password":"admin"
}
> {%
    client.test("Validate", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
        client.assert(response.body.data.accessToken.trim().length > 0);
    });

    client.log(response.body.data.accessToken);
    client.global.set("accessToken",response.body.data.accessToken)
%}