### Join
POST http://localhost:8080/api/members/join
Content-Type: application/json

{
    "name": "name",
    "email": "test",
    "nickName": "nickName",
    "password": "password",
    "checkPassword": "checkPassword"
}


### Login
POST http://localhost:8080/api/members/login
Content-Type: application/json

{
  "email": "test",
  "password": "password"
}
