###
GET http://localhost:8080/products?pageNumber=4&pageSize=5

###
GET http://localhost:8080/products/18

###
GET http://localhost:8080/products?sellerId=2&pageNumber=1&pageSize=5

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "something",
  "price": 10000,
  "quantity": 2
}

###
POST http://localhost:8080/products/19/orders
Content-Type: application/json

{
  "version": 0
}

###
POST http://localhost:8080/products/20/orders
Content-Type: application/json

{
  "version": 1
}

###
GET http://localhost:8080/products/my?pageNumber=1&pageSize=5

###
GET http://localhost:8080/products/my?hasOrder=true&pageNumber=1&pageSize=5
