# Generated by Django 4.2.13 on 2024-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_buyer_order_created_at_order_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='가격'),
        ),
    ]
