# Generated by Django 4.2.13 on 2024-06-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reservation_status',
            field=models.CharField(choices=[('판매중', 'Sale'), ('예약중', 'Reservations'), ('완료', 'Completed')], default='판매중', max_length=3),
        ),
    ]
