# Generated by Django 4.2.13 on 2024-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=5, verbose_name='수량'),
            preserve_default=False,
        ),
    ]
