# Generated by Django 4.2.13 on 2024-06-08 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ManyToManyField(blank=True, null=True, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
