# Generated by Django 4.2.13 on 2024-06-08 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_remove_order_buyer_order_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ManyToManyField(related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
